version: "3"



services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    container_name: zookeeper
#    ports:
#      - '2181:2181'

  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: DOCKER://:9092, LOCALHOST://:9082
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka1:9092, LOCALHOST://localhost:9082
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
     - "9082:9082"
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:6.2.0
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: DOCKER://:9092, LOCALHOST://:9083
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka2:9092, LOCALHOST://localhost:9083
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
       - "9083:9083"
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9092
    depends_on:
      - kafka1
      - kafka2
  tools:
    image: dancier/kafka-tools:latest
    stdin_open: true
    tty: true