spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka
    username: kafka
    password: kafka
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  test:
    database:
      replace: none

app:
  kafka:
    bootstrap-servers: localhost:9082